### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by agausachs** [GrafGenerator/ssrs-formularize#1]
Hi,

I have compiled the solution, deployed to SSRS, and restarted the service. I can see the new renderer in the dropdown but I don't know how to integrate it in a report. 
I have tried to create a new column in a tablix, and put "=ReportItems!TextBoxName.Value + ..." but still appears in Excel as a value not as a formula.

How can I do it?

Thanks in advance!

**Comment by GrafGenerator** [comment]
Hi @agausachs ,

Actually, the level of this extension integration into SSRS is not so big) SSRS engine parse formulas in report items, and there is no extension point to control this process. So this extension in fact is very hacky solution, it uses the only report item's property that is not transformed during rendering - action link (URL). In order to make it work you need to set link to special value, I'll check and post function that I wrote for this.

**Comment by GrafGenerator** [comment]
General idea is that you can put "anchors" that RE will recognize and use to reference in formulas, anchors can point to single cell, range (not sure, need to check) and whole row or column). Then you can put DSL formulas that will use anchors to build Excel formulas. See tests in the project, there you can see how it works.

**Comment by agausachs** [comment]
Thanks! I’ll tryit with the actionurl.

**Comment by GrafGenerator** [comment]
@agausachs I wrote some info to readme about usage (this should be done a long time ago, thanks for making me finally do it :)). Also, I created file encode-function.vb in root, you can use this function to generate formulas.

Check this and if all is fine, close the issue)

**Comment by agausachs** [comment]
Yes! It works! I followed your instructions and finally I made it work correctly. Thank you a lot!
P.S: There's an error on the vb code you posted. `"&amp;"` should be only "&". I think maybe was an error pasting the function on github. :-D

**Comment by agausachs** [comment]
My last comment has dissapeared. :-S
Thank you a lot. Following your instructions it works really well.
P.S: There's an issue on the vb code. On pasting on github has converted the amp character on `&amp;`

**Comment by GrafGenerator** [comment]
@agausachs it's great to know that all is fine! And thanks for pointing to issue with &, I copypasted from RDL and forgot that it's XML, so there is escaping :)
